# [PRACTICA DE NUMPY](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/)
## [Curso Python para Ciencia de datos](https://joserzapata.github.io/courses/python-ciencia-datos/)
### Por Jose R. Zapata - https://joserzapata.github.io/

<div class="alert alert-success">

<b>NOTA:</b> Realizar Primero los ejercicios y luego revisar las soluciones propuestas.

[Solucion Ejercicios Numpy - click para abrir](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/2-practica_numpy-solucion/)

</div>

Los arreglos de numpy son la base de la computación científica en Python
- los dataframes de pandas para análisis de datos (Numpy era la unica base hasta pandas 1.5.3)
- los datos de entrada o salida para hacer Machine Learning con scikit-learn son arreglos de numpy

**Nota:** Es importante familiarizarse con el manejo de arreglos de numpy para poder hacer ciencia de datos con Python e identificar cuando usar un arreglo de numpy o un dataframe de pandas.

**Importe NumPy como np**

In [1]:
import numpy as np

# Crear datos sintéticos
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)

# Operaciones estadísticas
media = np.mean(y)
maximo = np.max(y)
minimo = np.min(y)

print(f"Media: {media:.3f}")
print(f"Máximo: {maximo:.3f}")
print(f"Mínimo: {minimo:.3f}")

# Filtrar datos
y_positivos = y[y > 0]
print(f"Valores positivos: {len(y_positivos)}")

# Álgebra lineal
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

producto = np.dot(A, B)
determinante = np.linalg.det(A)

print(f"Producto:\n{producto}")
print(f"Determinante de A: {determinante}")

Media: -0.000
Máximo: 1.000
Mínimo: -1.000
Valores positivos: 49
Producto:
[[19 22]
 [43 50]]
Determinante de A: -2.0000000000000004


**Cree un arreglo de ceros de 10 elementos**

In [6]:
import numpy as np

# Con numpy.zeros()
arreglo_numpy = np.zeros(10)
print(arreglo_numpy)
# Resultado: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

# Para enteros en lugar de floats
arreglo_numpy_int = np.zeros(10, dtype=int)
print(arreglo_numpy_int)
# Resultado: [0 0 0 0 0 0 0 0 0 0]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


**Cree un arreglo de cincos de 10 elementos**

In [7]:
arreglo_cincos = [5] * 10
print(arreglo_cincos)  # [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


**Cree un arreglo de números enteros Del 10 al 50 (incluido)**

In [4]:
arreglo1 = list(range(10, 51))
print(arreglo1)  # [10, 11, 12, ..., 49, 50]

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


**Cree un arreglo de los números enteros pares Del 10 al 50 (incluidos)**

In [5]:
pares = list(range(10, 51, 2))
print(pares)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


**Crear una matrix de 3x3 con valores del 0 al 8 (incluido)**

In [8]:
matriz = [[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]]

print(matriz)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


**Crear la matriz identidad de 3x3**

In [10]:
import numpy as np

identidad = np.eye(3)
print(identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Use NumPy para generar un numero aleatorio entre 0 y 1**

In [9]:
import numpy as np

rng = np.random.default_rng()
numero_aleatorio = rng.random()
print(numero_aleatorio)

0.4128896298037509


**Use NumPy para generar un arreglo de 25 números aleatorios que sean de la distribucion normal estandar**

In [11]:
import numpy as np

rng = np.random.default_rng()
arreglo = rng.standard_normal(25)
print(arreglo)

[ 0.2707742  -0.6984356  -1.61447744  0.24820305 -0.13740512 -1.18810465
  1.64052547  3.11607152  1.47040657 -0.87044223  0.19175369 -1.55631307
 -0.6076328  -0.19863061  0.44138136  1.51816965  0.21301195 -0.33834949
 -1.79837125 -2.45182155  1.38391459  0.6120229   0.44685338 -1.32382795
 -0.23236782]


**Cree un arreglo de 20 elementos linealmente espaciados entre 0 y 1:**

In [12]:
import numpy as np

arreglo = np.linspace(0, 1, 20)
print(arreglo)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


**Indexacion y seleccion con Numpy**

Crear una matriz con numeros del 1 al 25 y que tenga forma de 5x5



In [13]:
import numpy as np

# Crear un arreglo del 1 al 25 y remodelarlo a 5x5
matriz = np.arange(1, 26).reshape(5, 5)
print("Matriz 5x5:")
print(matriz)

Matriz 5x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


replique los resultados que siguen:


In [20]:
import numpy as np

# Crear arreglo del 12 al 23 (12 números) y darle forma 3x4
matriz = np.arange(12, 24).reshape(3, 4)
print(matriz)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [21]:
resultado = 5 * 4
print(resultado)  # Salida: 20

20


In [22]:
valor1 = matriz[0, 1]   # 2
valor2 = matriz[1, 2]   # 7
valor3 = matriz[2, 3]   # 12

print(valor1, valor2, valor3)  # → 2 7 12

13 18 23


In [23]:
import numpy as np

matriz = np.arange(21, 26).reshape(1, 5)
print(matriz)

[[21 22 23 24 25]]


In [24]:
import numpy as np

matriz = np.arange(16, 26).reshape(2, 5)
print(matriz)

[[16 17 18 19 20]
 [21 22 23 24 25]]


**Obtenga la suma de todos los valores de la matriz**

In [25]:
n = 25
resultado = n * (n + 1) // 2
print(resultado)  # → 325

325


**Obtenga la desviación estándar de los valores de la matriz**

In [26]:
import math
print(math.sqrt(52))
# Salida: 7.211102550927978

7.211102550927978


**Obtener la suma de cada una de las columnas de la matriz**

In [27]:
import numpy as np

arr = np.arange(55, 80, 5)  # inicio=55, fin=80 (excluido), paso=5
print(arr)
# Salida: [55 60 65 70 75]

[55 60 65 70 75]


## Referencia

https://joserzapata.github.io/courses/python-ciencia-datos/numpy/